### ISSUE TITLE
poe开始收费了

### ISSUE THREAD

**Issue by meesii** [juzeon/poe-openai-proxy#11]
![image](https://user-images.githubusercontent.com/1815046/236914422-507c1977-5a5c-4304-998c-3a7724cbf155.png)

**Comment by juzeon** [comment]
收费方案应该还是和原来一样。即gpt-3.5模型和Claude-instant免费，gpt-4等收费。

近期只不过是增加了在网页版上进行订阅的功能。

**Comment by mmwong1984** [comment]
我可以低價升級帳號

**Comment by mmwong1984** [comment]
有需要電郵我
tszfeng43@gmail.com
