### ISSUE TITLE
Use another IP for api endpoint?

### ISSUE THREAD

**Issue by arjanflac** [juzeon/poe-openai-proxy#15]
Hello, I'm trying to figure out how to bind to a tailscale vpn IP instead of localhost as the endpoint  http://localhost:3700/v1/chat/completions  ----> http://100.x.y.z:3700/v1/chat/completions

This way I can keep this proxy running on my home server & access it via the server's Tailscale internal IP
Would it be easier to configure is using docker?

is this possible?

**Comment by juzeon** [comment]
The service will bind port 3700 to *every* IP belonging to the server, so just run it and here you go.
