### ISSUE TITLE
Failed to register token to Poe

### ISSUE THREAD

**Issue by XZ1314XZ** [juzeon/poe-openai-proxy#24]
I succeed to  use all funtion yesterday.But it start to be invalid today.
Of course, I guarantee that I have manually changed the token to verify that the token is real and usable.

There are the info in running `poe-openai-proxy`
```
INFO: registering client: failed: Invalid token or no bots are available.
```

**Comment by glidea** [comment]
+1

**Comment by fkx816** [comment]
use poe-api 0.4.5 may solve this problem

**Comment by XZ1314XZ** [comment]
Fine.Thanks.When I use 0.4.5 it works
