### ISSUE TITLE
docker部署请求报错500

### ISSUE THREAD

**Issue by LNpks** [juzeon/poe-openai-proxy#31]
docker 运行报错，
ERROR: registering client error: Post "http://localhost:5100/add_token": dial tcp 127.0.0.1:5100: connect: connection refused
然后post请求报错500 [GIN] 2023/06/26 - 04:54:53 | 500 |    2.694727ms |  xxxxxx | POST     "/v1/chat/completions"

**Comment by 79887143** [comment]
解决了吗老哥，我也500

**Comment by yyx20202020** [comment]
同样的问题，你解决了吗

**Comment by yyx20202020** [comment]
[http://localhost:5100]按照配置里面改成http://external:5100也不行，改成http:/ip:5100也不行，试了各种方法
