### ISSUE TITLE
Q about rate limit per client

### ISSUE THREAD

**Issue by LukasAndreano** [juzeon/poe-openai-proxy#4]
Hey!

What is the recommended rate limit per token per minute? Using 8 (lowered by 2 from the example), the token was banned after 10 minutes (requests were made 8 times/minute, without stopping).  Any ideas?

Thanks

**Comment by juzeon** [comment]
Seems that besides rate limit, they have implemented other methods to detect calls from reverse-engineered api. Currently we do not have a very effective way to solve this. 

One of my account was banned suddenly when I was using their web app normally, and that account was created just shortly after the public release of poe.

**Comment by LukasAndreano** [comment]
Could it be the IP? For example, I had about 30 clients, all from the same IP. Maybe you know, there is some kind of limit here...

**Comment by juzeon** [comment]
It's possible. You can set `proxy` to the endpoint of some round-robin proxy pool to do a test.

BTW, I have just pushed a new commit to add a cool down option to the code. Hope this can be mitigated.

**Comment by LukasAndreano** [comment]
In any case, I can specify one proxy, so in fact nothing will change here. 

About the commit: is the recommended parameter about 3?
And thank you!

**Comment by juzeon** [comment]
Well I have not tested the value yet.

As far as I'm converned, `poe-api` requires a websocket connection to their backend to receive responses, and the establish of that connection takes sort of considerable time. So it's some what hard to frequently change the IP address.

**Comment by LukasAndreano** [comment]
Okay, thank you!
I'll come back later if I have any questions.

**Comment by LukasAndreano** [comment]
I'm here XD.
Добавил 1 токен, поставил в минуту 8 запросов, наспамил 8 запросов и сервре начал уходить в 500. Кажется, ошибка неверная и тело ответа {}. Будто бы нужно 429 и какое-то тело? Или это ок? Спасибо

**Comment by LukasAndreano** [comment]
I added 1 token, put 8 queries per minute, spammed 8 queries and the servre started to go to 500. The error seems to be wrong and the response body {}. Like you need 429 and some body? Or is that ok? Thanks

**Comment by juzeon** [comment]
The server will report error if there's not available client (all in cool down state or rate limit is hit). You'd better register more accounts (like 10-20) and add their tokens to the configuration file.
