### ISSUE TITLE
希望可在在環境變數中增加tokens/ 以此項目作為一個中轉代理，以poe token為api key

### ISSUE THREAD

**Issue by mmwong1984** [juzeon/poe-openai-proxy#44]
例如
POE-TOKENS= your-poe-token

或是

請求的api key可以作為poe token

**Comment by juzeon** [comment]
你好，我沒有太聽明白你的意思，可以詳細描述一下你的需求嗎？

**Comment by mmwong1984** [comment]
以poe cookies作為api key 使用

**Comment by juzeon** [comment]
> 以poe cookies作為api key 使用

poe的cookies中包括一個token欄位，就是需要使用的cookies，只需要複製那個就行。

**Comment by mmwong1984** [comment]
以poe cookies作為openai 的api key 使用

**Comment by senqi77** [comment]
我想他的意思是，搭建出来只有代理地址，没有token，在接入程序中的key那一栏，没有可填写的值

**Comment by wingeva1986** [comment]
他的意思可能是想通过openai的消息层指定一个token，而不是从token池里轮询吧。我也有类似的需求，不走预设的token轮询，比如需要指定一些有订阅服务的token使用收费模型，但不是从openai消息去指定。
